-- 0001_foundation — Phase 1 identity, preferences, trip shell, audit.
--
-- Forward-only. Hand-authored rather than generated, because PostGIS types,
-- GiST indexes, partial unique indexes, check constraints and RLS policies are
-- not expressible in a TypeScript schema DSL (ADR-0004), and because a migration
-- that touches the security model must be readable in review.
--
-- Conventions (docs/phase-0/14-DATA-MODEL.md §1):
--   ids          uuid, generated by the application as UUIDv7
--   instants     timestamptz, always UTC
--   money        numeric(18,4) + char(3) ISO 4217, never float
--   points       geography(Point,4326)
--   soft delete  only where recovery or audit requires it

BEGIN;

-- ===========================================================================
-- Session context and RLS helpers
-- ===========================================================================

-- The current actor, set per transaction by the application. NULL when unset,
-- which makes every policy below evaluate false: a missing session is a closed
-- door rather than an open one.
CREATE OR REPLACE FUNCTION app.current_user_id() RETURNS uuid
  LANGUAGE sql STABLE
AS $$
  SELECT NULLIF(current_setting('app.current_user_id', true), '')::uuid
$$;

-- ===========================================================================
-- Enums — an invalid status is unwritable rather than merely discouraged
-- ===========================================================================
CREATE TYPE data_status  AS ENUM ('REALTIME','SCHEDULED','ESTIMATED','MANUAL','STALE','UNAVAILABLE');
CREATE TYPE trip_role    AS ENUM ('OWNER','EDITOR','VIEWER');
CREATE TYPE trip_status  AS ENUM ('PLANNING','UPCOMING','ACTIVE','PAST','ARCHIVED');
CREATE TYPE visibility   AS ENUM ('PRIVATE','LINK','MEMBERS');
CREATE TYPE unit_system  AS ENUM ('METRIC','IMPERIAL');
CREATE TYPE time_format  AS ENUM ('H12','H24');
CREATE TYPE travel_pace  AS ENUM ('RELAXED','BALANCED','INTENSIVE','CUSTOM');
CREATE TYPE ai_retention AS ENUM ('NONE','SESSION','RETAINED');
CREATE TYPE token_purpose AS ENUM ('EMAIL_VERIFY','PASSWORD_RESET');
CREATE TYPE coverage_tier AS ENUM ('T0','T1','T2','T3');

-- ===========================================================================
-- Identity
-- ===========================================================================
CREATE TABLE users (
  id                uuid PRIMARY KEY,
  email             citext NOT NULL UNIQUE,
  email_verified_at timestamptz,
  password_hash     text NOT NULL,
  display_name      text,
  home_iana_zone    text NOT NULL DEFAULT 'UTC',
  locale            text NOT NULL DEFAULT 'en',
  unit_system       unit_system NOT NULL DEFAULT 'METRIC',
  time_format       time_format NOT NULL DEFAULT 'H24',
  default_currency  char(3) NOT NULL DEFAULT 'MYR',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  deleted_at        timestamptz,
  CONSTRAINT users_currency_iso4217 CHECK (default_currency ~ '^[A-Z]{3}$')
);

CREATE TABLE auth_accounts (
  id                  uuid PRIMARY KEY,
  user_id             uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider            text NOT NULL,
  provider_account_id text NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_account_id)
);

-- Only a hash of the session token is stored; the raw token exists solely in the
-- user's cookie. IP and user-agent are hashed rather than stored raw — knowing a
-- session changed network is useful, knowing where someone was is a liability.
CREATE TABLE sessions (
  id              uuid PRIMARY KEY,
  user_id         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash      text NOT NULL UNIQUE,
  expires_at      timestamptz NOT NULL,
  absolute_expiry timestamptz NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  last_seen_at    timestamptz NOT NULL DEFAULT now(),
  user_agent_hash text,
  ip_hash         text,
  CONSTRAINT sessions_expiry_order CHECK (expires_at <= absolute_expiry)
);
CREATE INDEX sessions_user_idx    ON sessions (user_id);
CREATE INDEX sessions_expires_idx ON sessions (expires_at);

CREATE TABLE verification_tokens (
  id          uuid PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose     token_purpose NOT NULL,
  token_hash  text NOT NULL UNIQUE,
  expires_at  timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
-- Single-use is enforced in the UPDATE predicate (consumed_at IS NULL); this
-- partial index makes that lookup cheap and the intent explicit.
CREATE INDEX verification_tokens_live_idx
  ON verification_tokens (user_id, purpose) WHERE consumed_at IS NULL;

-- ===========================================================================
-- Preferences and privacy
-- ===========================================================================
CREATE TABLE user_preferences (
  user_id                 uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  interests               text[] NOT NULL DEFAULT '{}',
  dislikes                text[] NOT NULL DEFAULT '{}',
  pace                    travel_pace NOT NULL DEFAULT 'BALANCED',
  budget_amount           numeric(18,4),
  budget_currency         char(3),
  preferred_modes         text[] NOT NULL DEFAULT '{}',
  avoided_modes           text[] NOT NULL DEFAULT '{}',
  max_walk_meters_per_leg integer NOT NULL DEFAULT 1000,
  max_walk_meters_per_day integer NOT NULL DEFAULT 8000,
  min_transfer_seconds    integer NOT NULL DEFAULT 300,
  earliest_start          time NOT NULL DEFAULT '08:00',
  latest_finish           time NOT NULL DEFAULT '22:00',
  meal_windows            jsonb NOT NULL DEFAULT '[]'::jsonb,
  dietary                 text[] NOT NULL DEFAULT '{}',
  accessibility           jsonb NOT NULL DEFAULT '{}'::jsonb,
  indoor_outdoor_balance  smallint NOT NULL DEFAULT 50,
  travelling_with         jsonb NOT NULL DEFAULT '{}'::jsonb,
  nightlife               smallint NOT NULL DEFAULT 50,
  sustainability          smallint NOT NULL DEFAULT 50,
  buffer_minutes          integer NOT NULL DEFAULT 15,
  weather_tolerance       smallint NOT NULL DEFAULT 50,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  -- BR-P5 and BR-P6. A preference set that cannot admit a valid plan should be
  -- rejected at write time, not discovered by the constraint engine later.
  CONSTRAINT prefs_day_window   CHECK (earliest_start < latest_finish),
  CONSTRAINT prefs_walk_bounds  CHECK (max_walk_meters_per_leg <= max_walk_meters_per_day),
  CONSTRAINT prefs_walk_positive CHECK (max_walk_meters_per_leg > 0),
  CONSTRAINT prefs_budget_pair  CHECK (num_nonnulls(budget_amount, budget_currency) <> 1),
  CONSTRAINT prefs_sliders      CHECK (
    indoor_outdoor_balance BETWEEN 0 AND 100 AND nightlife BETWEEN 0 AND 100
    AND sustainability BETWEEN 0 AND 100 AND weather_tolerance BETWEEN 0 AND 100
  )
);

-- Every default here is the restrictive value: a user who never opens settings
-- is in the most private configuration (docs/phase-0/19-PRIVACY-AND-RETENTION.md §2).
CREATE TABLE user_privacy_settings (
  user_id                       uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  location_history_enabled      boolean NOT NULL DEFAULT false,
  analytics_enabled             boolean NOT NULL DEFAULT false,
  ai_input_retention            ai_retention NOT NULL DEFAULT 'SESSION',
  share_profile_on_shared_trips boolean NOT NULL DEFAULT false,
  export_requested_at           timestamptz,
  deletion_requested_at         timestamptz,
  created_at                    timestamptz NOT NULL DEFAULT now(),
  updated_at                    timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- Trip shell (extended in Phase 2)
-- ===========================================================================
CREATE TABLE trips (
  id             uuid PRIMARY KEY,
  owner_id       uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  title          text NOT NULL,
  status         trip_status NOT NULL DEFAULT 'PLANNING',
  start_date     date,
  end_date       date,
  traveler_count integer NOT NULL DEFAULT 1,
  tags           text[] NOT NULL DEFAULT '{}',
  visibility     visibility NOT NULL DEFAULT 'PRIVATE',
  notes          text,
  version        integer NOT NULL DEFAULT 1,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  deleted_at     timestamptz,
  CONSTRAINT trips_date_order   CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
  CONSTRAINT trips_travelers    CHECK (traveler_count > 0)
);
CREATE INDEX trips_owner_idx  ON trips (owner_id) WHERE deleted_at IS NULL;
CREATE INDEX trips_status_idx ON trips (status, start_date) WHERE deleted_at IS NULL;

CREATE TABLE trip_members (
  trip_id   uuid NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  user_id   uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role      trip_role NOT NULL,
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (trip_id, user_id)
);
CREATE INDEX trip_members_user_idx ON trip_members (user_id);

-- BR-TR2: exactly one owner per trip, always. A partial unique index makes an
-- ownerless or two-owner trip unrepresentable rather than merely discouraged,
-- so "owner leaves their own trip" fails at the database even if a service
-- check is missed.
CREATE UNIQUE INDEX trip_members_single_owner_idx
  ON trip_members (trip_id) WHERE role = 'OWNER';

-- Membership lookup used by every policy below. SECURITY DEFINER because a
-- policy on trip_members that consulted trip_members would recurse.
CREATE OR REPLACE FUNCTION app.is_trip_member(p_trip uuid) RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM trip_members m
    WHERE m.trip_id = p_trip AND m.user_id = app.current_user_id()
  )
$$;

CREATE OR REPLACE FUNCTION app.trip_role(p_trip uuid) RETURNS text
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
  SELECT m.role::text FROM trip_members m
  WHERE m.trip_id = p_trip AND m.user_id = app.current_user_id()
$$;

-- ===========================================================================
-- Audit and outbox
-- ===========================================================================

-- Append-only. No UPDATE or DELETE grant to any runtime role, so an audit trail
-- survives the actions it records — including the deletion of its own subject.
CREATE TABLE audit_events (
  id             uuid PRIMARY KEY,
  actor_id       uuid REFERENCES users(id) ON DELETE SET NULL,
  trip_id        uuid REFERENCES trips(id) ON DELETE CASCADE,
  action         text NOT NULL,
  target_type    text NOT NULL,
  target_id      uuid,
  metadata       jsonb NOT NULL DEFAULT '{}'::jsonb,
  correlation_id text,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_events_trip_idx        ON audit_events (trip_id, created_at DESC);
CREATE INDEX audit_events_correlation_idx ON audit_events (correlation_id);

-- Written in the same transaction as the state change it describes, so there is
-- never a dual-write between the database and an external system.
CREATE TABLE outbox_events (
  id             uuid PRIMARY KEY,
  aggregate_type text NOT NULL,
  aggregate_id   uuid NOT NULL,
  event_type     text NOT NULL,
  payload        jsonb NOT NULL,
  published_at   timestamptz,
  attempts       integer NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX outbox_unpublished_idx ON outbox_events (created_at) WHERE published_at IS NULL;

-- ===========================================================================
-- Row-level security (ADR-0009)
--
-- ENABLE alone is not enough: it does not apply to the table owner. FORCE is
-- what makes the policies bind, and the application connects as a non-owner
-- role so they actually restrain it.
-- ===========================================================================

ALTER TABLE users                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE users                 FORCE  ROW LEVEL SECURITY;
ALTER TABLE auth_accounts         ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_accounts         FORCE  ROW LEVEL SECURITY;
ALTER TABLE sessions              ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions              FORCE  ROW LEVEL SECURITY;
ALTER TABLE user_preferences      ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences      FORCE  ROW LEVEL SECURITY;
ALTER TABLE user_privacy_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_privacy_settings FORCE  ROW LEVEL SECURITY;
ALTER TABLE trips                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE trips                 FORCE  ROW LEVEL SECURITY;
ALTER TABLE trip_members          ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_members          FORCE  ROW LEVEL SECURITY;
ALTER TABLE audit_events          ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events          FORCE  ROW LEVEL SECURITY;

-- Tier 1 — owned directly by a user.
-- WITH CHECK matters as much as USING: without it a user could WRITE a row
-- belonging to someone else even while unable to read it.
CREATE POLICY users_self ON users
  USING (id = app.current_user_id())
  WITH CHECK (id = app.current_user_id());

CREATE POLICY auth_accounts_self ON auth_accounts
  USING (user_id = app.current_user_id())
  WITH CHECK (user_id = app.current_user_id());

CREATE POLICY sessions_self ON sessions
  USING (user_id = app.current_user_id())
  WITH CHECK (user_id = app.current_user_id());

CREATE POLICY user_preferences_self ON user_preferences
  USING (user_id = app.current_user_id())
  WITH CHECK (user_id = app.current_user_id());

CREATE POLICY user_privacy_self ON user_privacy_settings
  USING (user_id = app.current_user_id())
  WITH CHECK (user_id = app.current_user_id());

-- Tier 2 — reached through trip membership.
CREATE POLICY trips_member_read ON trips
  FOR SELECT USING (app.is_trip_member(id));

CREATE POLICY trips_owner_write ON trips
  FOR ALL
  USING      (app.trip_role(id) = 'OWNER')
  WITH CHECK (app.trip_role(id) = 'OWNER');

CREATE POLICY trip_members_read ON trip_members
  FOR SELECT USING (app.is_trip_member(trip_id));

CREATE POLICY trip_members_owner_write ON trip_members
  FOR ALL
  USING      (app.trip_role(trip_id) = 'OWNER')
  WITH CHECK (app.trip_role(trip_id) = 'OWNER');

-- Audit is readable by members of the trip it concerns, and by nobody else.
CREATE POLICY audit_events_read ON audit_events
  FOR SELECT USING (trip_id IS NOT NULL AND app.is_trip_member(trip_id));

CREATE POLICY audit_events_insert ON audit_events
  FOR INSERT WITH CHECK (true);

-- ===========================================================================
-- Grants
-- ===========================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON
  users, auth_accounts, sessions, verification_tokens,
  user_preferences, user_privacy_settings, trips, trip_members
TO travelplus_app;

-- Append-only: deliberately no UPDATE or DELETE (RLS test 9).
GRANT SELECT, INSERT ON audit_events TO travelplus_app;

-- Outbox belongs to the system worker; the app writes rows transactionally but
-- never drains them.
GRANT SELECT, INSERT ON outbox_events TO travelplus_app;
GRANT SELECT, INSERT, UPDATE ON outbox_events TO travelplus_worker_sys;

GRANT EXECUTE ON FUNCTION app.current_user_id()      TO travelplus_app, travelplus_worker_sys;
GRANT EXECUTE ON FUNCTION app.is_trip_member(uuid)   TO travelplus_app;
GRANT EXECUTE ON FUNCTION app.trip_role(uuid)        TO travelplus_app;

COMMIT;
